### ISSUE TITLE
Question change permission for pm-service

### ISSUE THREAD

**Issue by ale8530** [superr/make_ext4fs#1]
Hello superr,
thanks for this code.

I have an problem, set on Initial commit permission AID_SYSTEM AID_SYSTEM for system/bin/pm-service ,when make new make_ext4fs the permission of this file remain AID_ROOT AID_SHELL.

if use source nagouts the permission changed,but i have FC camera on HDR.

Why not change permission with android 6.0? it's work in my rom,but need change permission of this file

Thanks for your help

**Comment by superr** [comment]
The capabilities for that file are set here:
https://github.com/superr/make_ext4fs/blob/master/core/include/private/android_filesystem_config.h#L327

I am not sure I answered your question

**Comment by ale8530** [comment]
Thanks superr for your reply.

I have started from the first commit, I added the string relative to pm-service, but I do not change the permissions AID_SYSTEM AID_SYSTEM, but remain AID_ROOT AID_SHELL, may miss some setup?

**Comment by superr** [comment]
Make sure you use the proper syntax. It changed with the Nougat commit. It should be:
```
{ 00755, AID_SYSTEM,    AID_SYSTEM,    (1 << CAP_NET_BIND_SERVICE), "system/bin/pm-service" },
```

**Comment by ale8530** [comment]
I have insert your syntax from Initial commit (android 6.0.1.) but remain aid_root aid_shell, you have placed some bugs with the next commit?

**Comment by superr** [comment]
I am not aware of any bugs and many people use this source. If you figure out the problem let me know.

**Comment by ale8530** [comment]
I have resolve:

Cleaned up the code with nagouts fixes and added strings to fix and added contents.c and now has changed the permissions.

Thanks superr for all
