### ISSUE TITLE
create image with large file

### ISSUE THREAD

**Issue by joyway66** [superr/make_ext4fs#2]
if the target image folder such as system, it has some file that is large than 128MB(may be 124MB),
it will create a invalid image. with your make_ext4fs.exe  it creat well, but when i try to unpack it , it loss many file. 
 i use the source complie it with cygwin , and than try again , it show "Failed to create image system.img, removing it

**Comment by superr** [comment]
I can't speak to cygwin compilation, but I have not had any problems in Linux.
