### ISSUE TITLE
Information

### ISSUE THREAD

**Issue by ale8530** [superr/make_ext4fs#5]
I have update make_exfs for Oreo but insert this command ./make_ext4fs -T 0 -S file_contexts -l 1073741824 -a system system_new.img output/ not recreate system_new.img why?

I don't have problem with android 7.x

**Comment by superr** [comment]
Do you have make_ext4fs, file_contexts, and output in the same directory as your command requires? Is there anything in output/ ?

I just ran your command and did not see any issues:
```
$ ./make_ext4fs -T 0 -S file_contexts -l 1073741824 -a system system_new.img output/
Creating filesystem with parameters:
    Size: 1073741824
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8192
    Inode size: 256
    Journal blocks: 4096
    Label: 
    Blocks: 262144
    Block groups: 8
    Reserved block group size: 63
Created filesystem with 158/65536 inodes and 12013/262144 blocks
```

**Comment by ale8530** [comment]
my problem 

./make_ext4fs -T 0 -S file_contexts -l 5638709120 -a system system_new.img output/
Creating filesystem with parameters:
    Size: 5638705152
    Block size: 4096
    Blocks per group: 32768
    Inodes per group: 8016
    Inode size: 256
    Journal blocks: 21509
    Label: 
    Blocks: 1376256
    Block groups: 42
    Reserved block group size: 343
error: build_directory_structure: scandir: Permission denied

**Comment by superr** [comment]
"Permission denied". 

root owned files in output will fail.

**Comment by ale8530** [comment]
How resolve this problem?

**Comment by superr** [comment]
Change the ownership of the files in the output directory.
```
sudo chown -R user:user output/
```
Replace "user" above with your Linux username.

**Comment by ale8530** [comment]
Great very thanks! You have PayPal for donation?

**Comment by superr** [comment]
I do, thanks :)

[Donate link](https://forum.xda-developers.com/donatetome.php?u=5787964)
